adb shell pm uninstall --user 0 com.coloros.compass2
adb shell pm uninstall --user 0 com.heytap.market
adb shell pm uninstall --user 0 com.heytap.themestore
adb shell pm uninstall --user 0 com.oppo.lfeh
adb shell pm uninstall --user 0 com.xb.topnews
adb shell pm uninstall --user 0 com.coloros.appmanager
adb shell pm uninstall --user 0 com.coloros.musiclink
adb shell pm uninstall --user 0 com.coloros.childrenspace
adb shell pm uninstall --user 0 com.coloros.floatassistant
adb shell pm uninstall --user 0 com.nearme.romupdate
adb shell pm uninstall --user 0 com.oppo.otaui
adb shell pm uninstall --user 0 com.oppo.tzupdate
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.google.android.apps.youtube.music
adb shell pm uninstall --user 0 com.coloros.healthservice
adb shell pm uninstall --user 0 com.oppo.quicksearchbox
adb shell pm uninstall --user 0 com.oppo.usercenter
adb shell pm uninstall --user 0 com.coloros.safesdkproxy
adb shell pm uninstall --user 0 com.oppo.atlas
adb shell pm uninstall --user 0 com.heytap.mcs
adb shell pm uninstall --user 0 com.coloros.deepthinker
adb shell pm uninstall --user 0 com.facebook.system
adb shell pm uninstall --user 0 com.epi
adb shell pm uninstall --user 0 com.coloros.securepay
adb shell pm uninstall --user 0 com.oppo.logkit
adb shell pm uninstall --user 0 com.kwai.video
adb shell pm uninstall --user 0 com.trustonic.teeservice
adb shell pm uninstall --user 0 com.coloros.uxdesign
adb shell pm uninstall --user 0 com.facebook.katana
adb shell pm uninstall --user 0 com.heytap.datamigration
adb shell pm uninstall --user 0 com.tencent.soter.soterserver
adb shell pm uninstall --user 0 com.zing.mp3
adb shell pm uninstall --user 0 com.oppo.sos
adb shell pm uninstall --user 0 com.oppo.ota
adb shell pm uninstall --user 0 com.google.android.apps.photos
adb shell pm uninstall --user 0 com.UCMobile.intl
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.nearme.statistics.rom
adb shell pm uninstall --user 0 com.opera.browser
adb shell pm uninstall --user 0 com.coloros.sau
adb shell pm uninstall --user 0 com.coloros.backuprestore.remoteservice
adb shell pm uninstall --user 0 com.facebook.services
adb shell pm uninstall --user 0 com.google.android.setupwizard
adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.heytap.openid
adb shell pm uninstall --user 0 com.oppo.gmail.overlay
adb shell pm uninstall --user 0 com.oppo.partnerbrowsercustomizations
adb shell pm uninstall --user 0 com.oppoex.afterservice
adb shell pm uninstall --user 0 com.heytap.habit.analysis
adb shell pm uninstall --user 0 com.zing.zalo
adb shell pm uninstall --user 0 com.heytap.pictorial
adb shell pm uninstall --user 0 com.google.android.youtube
adb shell pm uninstall --user 0 com.coloros.weather.service
adb shell pm disable-user --user 0 com.coloros.weather2
adb shell pm uninstall --user 0 com.coloros.widget.smallweather


adb shell pm uninstall --user 0 com.color.uiengine
adb shell pm uninstall --user 0 com.coloros.oppomultiapp
adb shell pm uninstall --user 0 com.oppo.music
adb shell pm uninstall --user 0 com.heytap.browser
adb shell pm uninstall --user 0 com.coloros.phonemanager
adb shell pm uninstall --user 0 com.coloros.oppopods

adb shell pm uninstall --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall --user 0 com.coloros.oshare
adb shell pm uninstall --user 0 com.coloros.providers.downloads.ui

adb shell pm uninstall --user 0 com.oppo.operationManual
adb shell pm uninstall --user 0 com.coloros.gamespace
adb shell pm uninstall --user 0 com.heytap.cloud
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.coloros.backuprestore


adb shell pm uninstall --user 0 com.mediatek.sensorhub.ui
adb shell pm uninstall --user 0 com.mediatek.lbs.em2.ui
adb shell pm uninstall --user 0 com.mediatek.mdmconfig
adb shell pm uninstall --user 0 com.mediatek.gnssdebugreport
adb shell pm uninstall --user 0 com.mediatek.capctrl.service
adb shell pm uninstall --user 0 com.mediatek.atmwifimeta
adb shell pm uninstall --user 0 com.mediatek.security.service
adb shell pm uninstall --user 0 com.mediatek.frameworkresoverlay
adb shell pm uninstall --user 0 com.mediatek.mdmlsample
adb shell pm uninstall --user 0 com.mediatek.security
adb shell pm uninstall --user 0 com.mediatek.ims

adb shell pm uninstall --user 0 com.heytap.colorfulengine
adb shell pm uninstall --user 0 com.oppo.gestureservice
adb shell pm uninstall --user 0 com.oppo.rftoolkit
adb shell pm uninstall --user 0 com.coloros.exserviceui
adb shell pm uninstall --user 0 com.nearme.atlas
adb shell pm uninstall --user 0 com.oppo.qualityprotect
adb shell pm uninstall --user 0 com.oppo.engineermode.camera
adb shell pm uninstall --user 0 com.coloros.providers.fileinfo
adb shell pm uninstall --user 0 com.coloros.sceneservice
adb shell pm uninstall --user 0 com.oppo.resmonitor
adb shell pm uninstall --user 0 com.daemon.shelper
adb shell pm uninstall --user 0 com.coloros.smartdrive
adb shell pm uninstall --user 0 android.autoinstalls.config.oppo
adb shell pm uninstall --user 0 com.oppo.postmanservice
adb shell pm uninstall --user 0 com.coloros.assistantscreen
adb shell pm uninstall --user 0 com.coloros.activation
adb shell pm uninstall --user 0 com.ted.number
adb shell pm uninstall --user 0 com.coloros.bootreg
adb shell pm uninstall --user 0 com.coloros.wifibackuprestore
adb shell pm uninstall --user 0 com.coloros.healthcheck
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.android.statementservice
pause
